import { ArrowUpRight } from "lucide-react";
import { faqs } from "@/data/content";
import { siteConfig } from "@/config/site";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { SectionHeading } from "@/components/ui/section-heading";

export function Faq() {
  return <section id="faq" className="bg-page py-[clamp(96px,10vw,160px)] max-[640px]:py-[72px]"><Container><div className="grid grid-cols-[.8fr_1.2fr] gap-[9%] max-[900px]:grid-cols-1 max-[900px]:gap-[50px]"><SectionHeading eyebrow="FAQ" title={<>Pertanyaan yang<br /><em className="not-italic text-[#789700]">sering ditanyakan.</em></>} /><div className="border-t border-line">{faqs.map(([question, answer]) => <details className="group border-b border-line" key={question}><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-6 font-display text-[21px] font-semibold tracking-[-.025em] [&::-webkit-details-marker]:hidden max-[640px]:py-5 max-[640px]:text-[19px]">{question}<span className="text-[26px] font-light transition-transform group-open:rotate-45">+</span></summary><p className="mt-0 max-w-[680px] pb-6 text-ink-soft max-[640px]:text-[15px]">{answer}</p></details>)}</div></div></Container></section>;
}

export function FinalCta() {
  return <section id="kontak" data-navbar-tone="dark" className="relative isolate overflow-hidden bg-ink py-[130px] text-page max-[640px]:py-[90px]"><div aria-hidden="true" className="pointer-events-none absolute -left-[36%] -top-[60%] size-[950px] rounded-full border border-[#c4ef3548] max-[640px]:-left-[78%] max-[640px]:-top-[30%] max-[640px]:size-[650px]" /><div aria-hidden="true" className="pointer-events-none absolute -right-[25%] -top-[68%] size-[920px] rounded-full border border-[#ffffff21] max-[640px]:-right-[72%] max-[640px]:-top-[24%] max-[640px]:size-[600px]" /><Container className="relative z-[1] text-center"><p className="flex items-center justify-center gap-3 text-[11px] font-bold uppercase tracking-[.22em] text-[#d7dad2]"><span className="size-1.5 rounded-full bg-lime" /> Mulai Project</p><h2 className="mx-auto my-9 max-w-[1100px] font-display text-[clamp(58px,7vw,106px)] font-bold leading-[.9] tracking-[-.06em] max-[640px]:text-[48px]"><span>Mari membangun sesuatu</span><br />yang <em className="font-serif font-normal not-italic text-lime">menggerakkan bisnis Anda.</em></h2><div className="flex items-center justify-center gap-6 max-[640px]:flex-col"><Button className="border-page bg-page text-ink max-[640px]:w-full" href={siteConfig.whatsapp} arrow>Mulai Project</Button><i className="h-9 w-px bg-[#f2f5ec72] max-[640px]:h-px max-[640px]:w-[55px]" /><p className="m-0 flex items-center gap-1 text-[16px] text-[#c5c8c1] max-[640px]:flex-wrap max-[640px]:justify-center max-[640px]:text-[14px]">Lebih suka email? <a className="text-page hover:text-lime" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> <ArrowUpRight aria-hidden="true" size={17} /></p></div></Container></section>;
}
