import { ArrowUpRight } from "lucide-react";
import { projects } from "@/data/content";
import { Container } from "@/components/ui/container";
import { ProjectMockup } from "@/components/shared/project-mockups";

function ProjectLink() { return <a className="flex items-center justify-end gap-3.5 whitespace-nowrap text-[13px] font-bold" href="#kontak"><span className="grid size-[47px] place-items-center rounded-full border border-ink transition hover:-translate-y-1 hover:bg-lime"><ArrowUpRight size={20} /></span>Lihat Studi Kasus</a>; }
function ProjectMeta({ project, compact = false }: { project: (typeof projects)[number]; compact?: boolean }) { return <div className={`grid items-center gap-[5%] pt-7 ${compact ? "grid-cols-[1fr_.34fr]" : "grid-cols-[1.25fr_1fr_.42fr]"} max-[1050px]:grid-cols-2 max-[640px]:grid-cols-1 max-[640px]:gap-[18px]`}><div className="flex items-center gap-[17px] max-[640px]:gap-[11px]"><strong className="font-display text-[31px] font-medium tracking-[-.05em] text-muted max-[640px]:text-[24px]">{project.number}</strong><i className="h-px w-11 bg-lime-strong max-[640px]:w-[30px]" /><div><h3 className="m-0 font-display text-[clamp(30px,3vw,48px)] leading-none tracking-[-.055em] max-[640px]:text-[31px]">{project.title}</h3><p className="mt-2.5 text-[10px] font-semibold uppercase tracking-[.18em] text-[#737871]">{project.category}</p></div></div><p className={`m-0 max-w-[350px] text-[14px] leading-[1.45] text-ink-soft max-[1050px]:col-start-1 max-[640px]:col-auto max-[640px]:pl-[65px] max-[640px]:text-[14px] ${compact ? "max-[1050px]:pl-[92px]" : ""}`}>{project.description}</p><div className="max-[1050px]:col-start-2 max-[1050px]:row-span-2 max-[1050px]:justify-self-end max-[640px]:col-auto max-[640px]:row-auto max-[640px]:justify-self-start max-[640px]:pl-[65px]"><ProjectLink /></div></div>; }

export function Projects() { const [featured,...secondary] = projects; return <section id="portofolio" className="relative overflow-hidden bg-page py-[clamp(96px,10vw,160px)] max-[640px]:py-[72px]"><Container><header className="grid grid-cols-[1.35fr_.65fr] items-end gap-[9%] max-[1050px]:grid-cols-1 max-[1050px]:gap-[35px]"><div><p className="m-0 text-[12px] font-bold uppercase tracking-[.12em] text-ink-soft"><span className="mr-2.5 text-[16px] text-lime-strong">•</span>Project pilihan</p><h2 className="mt-6 max-w-[760px] font-display text-[clamp(52px,5.6vw,86px)] font-bold leading-[.91] tracking-[-.06em] max-[640px]:text-[43px]">Pilihan karya yang dibuat untuk <em className="not-italic text-[#96ce09]">menciptakan dampak.</em></h2></div><div className="max-w-[385px] pb-2"><p className="m-0 text-[17px] leading-[1.45] text-ink-soft">Dari platform digital dan e-commerce hingga sistem internal dan produk berbasis AI, kami merancang solusi berdasarkan kebutuhan bisnis nyata.</p><a className="mt-6 inline-flex items-center gap-2 border-b border-ink pb-2 text-[14px] font-bold" href="#portofolio">Lihat Semua Project <ArrowUpRight size={16} /></a></div></header><article className="mt-[74px]"><div className="h-auto"><ProjectMockup variant={featured.variant} /></div><ProjectMeta project={featured} /></article><div className="mt-[72px] grid grid-cols-2 gap-7 max-[1050px]:grid-cols-1 max-[640px]:mt-[62px] max-[640px]:gap-[65px]">{secondary.map((project)=><article key={project.number}><div className="h-[clamp(270px,29vw,420px)]"><ProjectMockup variant={project.variant} /></div><ProjectMeta compact project={project} /></article>)}</div></Container></section>; }
