import { processSteps, values } from "@/data/content";
import { Container } from "@/components/ui/container";
import { SectionHeading } from "@/components/ui/section-heading";

export function WhyUs() { return <section id="tentang" className="bg-page py-[clamp(96px,10vw,160px)] max-[640px]:py-[72px]"><Container><div className="grid grid-cols-[1.2fr_.8fr] gap-[9%] max-[900px]:grid-cols-1 max-[900px]:gap-7"><SectionHeading eyebrow="Kenapa kami" title={<>Bukan sekadar website yang <em className="not-italic text-[#789700]">terlihat bagus.</em></>} /><p className="max-w-[500px] self-end text-ink-soft">Kami membangun website yang cepat, mudah digunakan, scalable, dan siap mendukung pertumbuhan bisnis.</p></div><div className="mt-[74px] grid grid-cols-3 gap-7 border-t border-line max-[900px]:mt-[55px] max-[900px]:grid-cols-1 max-[640px]:mt-[55px]">{values.map((value) => <article className="border-b border-line py-7" key={value.number}><span className="font-display text-[17px] text-muted">{value.number}</span><h3 className="my-7 font-display text-[32px] font-semibold leading-none tracking-[-.03em]">{value.title}</h3><p className="m-0 max-w-[330px] text-ink-soft">{value.description}</p></article>)}</div></Container></section>; }

export function Metrics() { return <section className="bg-page py-[clamp(96px,10vw,160px)] max-[640px]:py-[72px]"><Container><p className="max-w-[900px] font-display text-[clamp(40px,4.5vw,64px)] font-bold leading-[.98] tracking-[-.045em]">Setiap project dimulai dengan memahami <em className="not-italic text-[#789700]">masalah</em>, bukan memilih template.</p><div className="mt-[75px] grid grid-cols-3 gap-8 border-t border-line pt-7 max-[900px]:grid-cols-2 max-[640px]:mt-[58px] max-[640px]:grid-cols-1">{[["Cepat.","Performa menjadi bagian dari proses, bukan optimasi di akhir."],["Custom.","Solusi mengikuti kebutuhan bisnis, bukan batasan template."],["Siap.","Arsitektur disiapkan untuk digunakan, dipelihara, dan dikembangkan."]].map(([title, description]) => <article key={title}><strong className="font-display text-[clamp(58px,7vw,96px)] font-bold leading-none tracking-[-.07em]">{title.slice(0,-1)}<span className="text-[#789700]">.</span></strong><p className="mt-4 max-w-[250px] text-ink-soft">{description}</p></article>)}</div></Container></section>; }

export function Process() { return <section id="proses" className="relative isolate overflow-hidden bg-page py-[clamp(96px,10vw,160px)] max-[640px]:py-[72px]"><div aria-hidden="true" className="pointer-events-none absolute -right-[520px] top-[26%] size-[900px] rounded-full border border-[#b7ca684d] opacity-60" /><Container><SectionHeading eyebrow="Proses kerja" title={<>Proses yang jelas.<br /><em className="not-italic text-[#789700]">Tanpa drama.</em></>} description="Setiap tahapan memiliki tujuan, output, dan keputusan yang jelas agar project tetap bergerak tanpa komunikasi yang rumit." /><div className="relative mt-[75px] grid grid-cols-5 gap-7 border-t border-line pt-7 max-[900px]:grid-cols-3 max-[640px]:mt-[65px] max-[640px]:grid-cols-1 max-[640px]:gap-6 max-[640px]:border-l max-[640px]:border-t-0 max-[640px]:py-0 max-[640px]:pl-[52px]">{processSteps.map(([number,title,description]) => <article className="relative" key={number}><span className="font-display text-[17px] text-muted">{number}</span><h3 className="my-3 font-display text-[24px] font-semibold leading-none tracking-[-.03em]">{title}</h3><p className="m-0 text-[15px] text-ink-soft">{description}</p></article>)}</div></Container></section>; }
