import { ArrowRight } from "lucide-react";
import { faqs, features, plans } from "@/lib/content";
import { Cta } from "./site-header";
import { Heading, Section } from "./section-primitives";
export function Pricing(){return <Section id="pricing" className="pricing"><div className="title-row"><Heading>Extensive Pricing Plans</Heading><p>Doubts? Reach out to us at <a href="mailto:contact@aceternity.com">contact@aceternity.com</a> or <a href="#contact">chat with us</a></p></div><div className="pricing-grid">{plans.map(plan=><article className={`plan ${plan.dark?"plan-dark":""}`} key={plan.label}><div className="plan-main"><div className="plan-tag"><span>{plan.label}</span><em>{plan.availability}</em></div><h3>{plan.title}<small>{plan.subtitle}</small></h3><div className="plan-bottom"><strong>{plan.price}<small>/mo</small></strong><Cta href="#contact">Select Plan</Cta></div><div className="review-pill">●　Jason Ray, CEO<br/><b>Aceternity and Manu are Cracked Devs!</b></div></div><ul>{features.map(feature=><li key={feature}>{feature}</li>)}</ul></article>)}</div></Section>}
export function Founder(){return <Section className="founder"><div className="founder-image"><span>MANU<br/>ARORA</span><i/></div><div><p className="eyebrow">The Founder’s Desk</p><h2>Building websites that become your best salesperson.</h2><p>I’m Manu, founder of Aceternity. We help ambitious teams turn unclear product stories into focused, conversion-ready web experiences.</p><a href="#contact">Chat with me <ArrowRight size={16}/></a></div></Section>}
export function Testimonials(){return <Section className="testimonials"><div className="title-row"><Heading>What people have been saying</Heading><Cta>Chat with us</Cta></div><div className="testimonial-grid"><article><b>Cal.com</b><p>“Working with Manu and his team was a masterclass in design engineering. They didn’t just create a website they built a high-performance, thoughtfully engineered product.”</p><footer><strong>Jack Hudson</strong>　VP of Engineering, Cal.com</footer></article><article><b className="google">G</b><p>“Manu&apos;s team rapidly iterated with our stakeholders and delivered a thoughtful, usable product that exceeded expectations.”</p><footer><strong>Priya Singh</strong>　Product Manager, Google</footer></article></div><div className="pager"><i/><i/><i/><i/><i/></div></Section>}
export function Faq(){return <Section className="faq"><div><Heading>Frequently Asked Questions</Heading><p>Have more doubts? Reach out to us at <a href="mailto:contact@aceternity.com">contact@aceternity.com</a></p><article><h3>Need a fast moving team of engineers for your startup?</h3><p>Aceternity is your best bet, we have designers, engineers and managers to take your project from 0-1.</p><Cta/></article></div><div className="faq-list">{faqs.concat(faqs.slice(3)).map(([question,answer],index)=><details key={`${question}-${index}`}><summary>{question}</summary><p>{answer}</p></details>)}</div></Section>}
export function Footer(){return <footer id="contact" className="footer"><div className="footer-cta"><h2>Make Your Website<br/>a Sales Machine</h2><Cta>Chat with Alex</Cta></div><div className="footer-links"><div><b>▲</b><p>Design and development for fast-moving companies.</p></div>{[["Home","Overview","Features","Pricing","Testimonials","FAQs"],["About","Our Story","Team","Careers","Blog","Press Kit"],["Contact","Contact Us","Support","Live Chat","Help Center","Report Issue"],["Legal","Privacy Policy","Terms of Service","Cookie Policy","Licenses","Security"]].map(([head,...items])=><div key={head}><h3>{head}</h3>{items.map(item=><a key={item} href="#top">{item}</a>)}</div>)}</div><small>© 2026 Aceternity. All rights reserved.</small></footer>}
